### PR TITLE
Started working on TC

### PR DESCRIPTION
**Pull request by dilaraturkcan**
please review my code

### CODE REVIEW

**Comment by sshukhratov** [comment]
Hello team

**Comment by FaridaAslan** [comment]
it is only fair if Abzal reviews your codes as well! :) Abzal, let's discuss! ;)

**Comment by FaridaAslan** [comment]
Hello, Sardor!

**Comment by dilaraturkcan** [comment]
Abzal please review my code

**Comment by sshukhratov** [comment]
Abzal is messing around

**Pull request merged**
